cat >> /etc/httpd/conf/maxclients.conf <<EOF
<IfModule prefork.c>
StartServers       2
MinSpareServers    2
MaxSpareServers   100
ServerLimit       9
MaxClients         9
MaxRequestsPerChild  4000
</IfModule>

<IfModule worker.c>
StartServers         2
MaxClients         9
MinSpareThreads     25
MaxSpareThreads     75
ThreadsPerChild     25
MaxRequestsPerChild  0
</IfModule>


<IfModule itk.c>
StartServers       2
MinSpareServers    2
MaxSpareServers   4
ServerLimit      9
MaxClients       9
MaxRequestsPerChild  4000
</IfModule>
EOF
sed -i 's/9/15/' /etc/httpd/conf/maxclients.conf
