cat >> /etc/munin/munin.conf <<EOF
dbdir	/var/lib/munin
htmldir /var/www/html/munin
logdir /var/log/munin
rundir  /var/run/munin
cgitmpdir /var/tmp
includedir /etc/munin/conf.d
graph_strategy cron
cgiurl_graph /munin-cgi/munin-cgi-graph
html_strategy cron
[localhost]
    address 127.0.0.1
    use_node_name yes
EOF

